{% set name = "mpltoolbox" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpltoolbox-{{ version }}.tar.gz
  sha256: 487dcf61b0767d6fff3e3c68eab6fcb2a2f5fcb1317554b8696135918216d044

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numpy

test:
  imports:
    - mpltoolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mpltoolbox/mpltoolbox
  summary: Interactive tools for matplotlib
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nvaytet
